"""initial schema baseline (stamped)

This is a "stamp" migration — it represents the initial database schema
that was created by infra/postgres/init.sql (tables: vehicles, drivers,
optimization_runs, orders, routes, route_stops, telemetry, geocode_cache).

Why an empty migration instead of autogenerate?
The database already has all tables from init.sql. If we autogenerated,
the migration would contain CREATE TABLE for tables that already exist,
which would fail on `alembic upgrade head`. Instead, we create this empty
migration and run `alembic stamp head` to tell Alembic "the DB is already
at this version." Future schema changes will be autogenerated diffs from here.

See: https://alembic.sqlalchemy.org/en/latest/cookbook.html#building-an-up-to-date-database-from-scratch

Revision ID: 215c8204dc10
Revises:
Create Date: 2026-02-22 00:28:27.912008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215c8204dc10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op: initial schema already exists from infra/postgres/init.sql."""
    pass


def downgrade() -> None:
    """No-op: dropping the entire schema is handled by Docker volume reset."""
    pass
